overwrite: true
schema: "https://mahalekshmi.ceymox.xyz/graphql"
documents: null
generates:
  types/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
      - "typescript-document-nodes"
  ./graphql.schema.json:
    plugins:
      - "introspection"